import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="text-2xl px-10 pt-5">
          <Link href="/">
            SIMPLE <span className="text-teal-400 font-semibold">Movie</span>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
